version: "3.9"
services:
  slither:
    build:
      context: .
      dockerfile: Dockerfile.slither
    container_name: slither

  mythril:
    build:
      context: .
      dockerfile: Dockerfile.mythril
    container_name: mythril

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: api
    ports:
      - "8000:8000"
    depends_on:
      - slither
      - mythril
    env_file:
      - .env  # Load environment variables (Etherscan, OpenAI keys, etc.)
    volumes:
      - ./tmp_data:/app/tmp_data  # Ensure temp storage persists across restarts
    restart: unless-stopped  # Ensures the API restarts if it crashes
